version: '3'

tasks:
  prerequisites:
    run: always
    dir: ./.
    cmds:
      - cp .githooks/pre-push .git/hooks/pre-push && chmod +x .git/hooks/pre-push

  fmt:
    run: always
    deps: [prerequisites]
    dir: ./.
    cmds:
      - go fmt ./...

  vet:
    run: always
    deps: [prerequisites, fmt]
    dir: ./.
    cmds:
      - go vet ./...

  build:
    run: always
    deps: [prerequisites, vet]
    dir: ./.
    cmds:
      - go build ./...

  test:
    run: always
    deps: [prerequisites]
    dir: ./.
    cmds:
      - go test ./... {{.CLI_ARGS}} 
    
  local-goherent:
    run: always
    deps: [prerequisites]
    dir: ./.
    cmds:
      - go run main.go {{.CLI_ARGS}}

  goherent:
    run: always
    deps: [prerequisites]
    dir: ./.
    cmds:
      - go run github.com/redjolr/goherent {{.CLI_ARGS}} 
